---
title: "On-going Funded Projects 2021"
description: |
   QML members are active in externally funded projects. Here is a list of on-going funded projects by QML members as of May 2021.
author:
  - name: Akihito Kamata
    url: {}
date: 05-27-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Kamata, A., Potgieter, C.**, Nese, J. F., & **Kara, Y.** Developing Computational Tools for Model-based Oral Reading Fluency Assessments. Funded by Institute of Educational Science - U.S. Department of Education to Southern Methodist University (August 2020 – July 2023). Total award $899,901.  

Nese, J. F., **Kamata, A.**, Saez, L., & Nese, R. A Comprehensive Measure of Reading Fluency: Uniting and Scaling Accuracy, Rate, and Prosody. Funded by Institute of Educational Science - U.S. Department of Education to University of Oregon (July 2020 – June 2024). Total award $1,399,379.  

Baker, D., **Kamata, A.**, Larson, E., Richards-Tutor, C. Measuring the English Language Vocabulary Acquisition of Latinx Bilingual Students (Project MELVA-S). Funded by Institute of Educational Science - U.S. Department of Education to Southern Methodist University (August 2020 – July 2024). Total award $1,399,943.  
